### ISSUE TITLE
Add support for NavPanelExpandToCurrentFolder?

### ISSUE THREAD

**Issue by Skatterbrainz** [jaapbrasser/CustomizeWindows11#10]
Any chance you could add something like Set-ExplorerExpandToCurrentFolder (using the registry key value above)?  If you already have it, please point me to the function (i may be blind).  Thank you!

**Comment by jaapbrasser** [comment]
Sweet, that functionality indeed wasn't there yet. I added the following functions to solve your issue and some of the other (not yet all) explorer nav bar options:

`Get-ExplorerNavExpandToCurrentFolder`
`Get-ExplorerNavShowAllFolder`
`Get-ExplorerNavShowAvailabilityStatus`
`Get-ExplorerNavShowLibrary`
`Set-ExplorerNavExpandToCurrentFolder`
`Set-ExplorerNavShowAllFolder`
`Set-ExplorerNavShowAvailabilityStatus`
`Set-ExplorerNavShowLibrary`

Let me know how that works for you! New release is available on GitHub and on PSGallery

**Comment by Skatterbrainz** [comment]
Sweet indeed!  Thanks!
